name: Continuous Integration

on: [push]

jobs:
  build-vscode:
    name: Build the VSCode extension
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 20.x
    - run: npm install -g typescript
    - run: npm install -g vsce
    - run: npm install
    - name: Package VSCode extension into .vsix file
      run: vsce package
