# This is a copy-and-past version of ci.yml but additionally creating a release
name: Release Artifacts

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build-vscode:
    name: Build the VSCode extension
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install -g typescript
    - run: npm install -g vsce
    - run: npm install
    - name: Package VSCode extension into .vsix file
      run: vsce package --out effekt.vsix

    - name: Upload vsix file
      uses: actions/upload-artifact@v1
      with:
        name: effekt-vscode
        path: effekt.vsix

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-vscode]
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Download VSCode artifact
        uses: actions/download-artifact@v1
        with:
          name: effekt-vscode
          path: distribution/

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: Prerelease ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body: Automatic release for ${{ github.ref }}
          draft: false
          prerelease: true

      - name: Upload vsix file
        id: upload_vsix
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./distribution/effekt.vsix
          asset_name: effekt-vscode-extension.vsix
          asset_content_type: application/zip
